name: checkin

on:
  schedule:
    - cron: '00 04 * * *'
    # 每天中午12点签到

  workflow_dispatch: # click the button on Github repo!

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      - run: yarn
      - uses: maufrontier/puppeteer-headful@v3
        env:
          CI: 'true'
          SEND_MAIL: ${{ secrets.SEND_MAIL }}
          RECEIVE_MAIL: ${{ secrets.RECEIVE_MAIL }}
          TOKEN: ${{ secrets.TOKEN }}
          URL: ${{ secrets.URL }}
          LOGIN_MAIL: ${{ secrets.LOGIN_MAIL }}
          LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
        with:
          commands: yarn start
