name: checkin

on:
  schedule:
    - cron: '00 04 * * *'
    # 每天中午12点签到

  workflow_dispatch: # click the button on Github repo!

env:
  SEND_MAIL: ${{ secrets.SEND_MAIL }}
  RECEIVE_MAIL: ${{ secrets.RECEIVE_MAIL }}
  TOKEN: ${{ secrets.TOKEN }}
  URL: ${{ secrets.URL }}
  COOKIE: ${{ secrets.COOKIE }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn
      - run: yarn start
